default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5

development:
  <<: *default
  database: gas_rails_development

test:
  <<: *default
  database: gas_rails_test

production:
  <<: *default
  database: gas_rails_production
